import os

def set_connections():
    os.environ["OPENAI_API_TYPE"] = 'api_key'
    os.environ["OPENAI_API_KEY"] = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    os.environ["OPENAI_EMBED_API_KEY"] = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    os.environ["AZURE_ENDPOINT1"] = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    os.environ["AZURE_ENDPOINT2"] = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    os.environ["AZURE_GPT_DEPLOY"] = 'XXXXXXXXXXXXXXXXXX'
    os.environ["AZURE_EMBED_DEPLOY"] = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
    os.environ["OPENAI_API_VERSION"] = '2023-12-01-preview'   #Es posible que esta versión nos joda un poco